### ISSUE TITLE
Potential for Infrared Support?

### ISSUE THREAD

**Issue by BowkC** [ITDev93/SHM-MOD#3]
Hello!
Love SHM it works wonders. On my Galaxy Watch Classic 6 I've noticed that the infrared sensor which should be disabled while sleep mode is enabled (or "bedtime mode") is never used and the green sensor is always used instead by the watch. I have come to the conclusion having explored other avenues to get it to function, as did Samsung support I spoke to (although the support agent I spoke to was incredibly unhelpful and could well have been wrong) that this feature allowing for the use of infrared sensors for sleep tracking and not green visible light sensors is locked to Galaxy devices. Would love to see this added to SHM in future. 

If the feature is not Galaxy-locked, apologies in advance for the unnecessary creation of a feature request. 
Thank you.

**Comment by ITDev93** [comment]
The issue you're referring to is part of Samsung Health, not part of SHM, and Samsung Health is not something that can be patched easily due to it being core application with server connectivity, modding SHealth will break most services and features...

I'm aware of Samsung support, i have been through that and they never were of help when i was in need of health data restore, lost 6 years of Samsung Health Data, as for restriction, i doubt it's galaxy locked, when you're sleeping, the watch should switch to red light instead of green (i might be wrong as i never reallybotheredto check if it does really switch or not)...

You can always visit Samsung Centre for support, better than the online support...

**Comment by BowkC** [comment]
Sure. I can imagine how difficult it'd be to mod the main Samsung health app so fair enough. Thank you for the helpful advice regarding support, they really don't help much online! Hopefully this is patched by Samsung in the not too distant future. 

I've seen it use red light for blood oxygen numerous times but HR is always green. I believe the combination of both red and green or red and infrared enables the measurement of blood oxygen on the device. It seems their implementation of sleep mode doesn't seem to work for everyone as advertised. 

In any case thanks again for your valuable insight.
